import type { Metadata } from 'next';
import { Roboto, Roboto_Mono, Roboto_Serif } from 'next/font/google';
import { headers } from 'next/headers';
import { Toaster } from 'sonner';
import { SiteHeader } from '@/components/site-header';
import { SiteFooter } from '@/components/site-footer';
import { Analytics } from '@/components/analytics/analytics';
import './globals.css';

const robotoSerif = Roboto_Serif({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-roboto-serif',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700'],
  display: 'swap',
  variable: '--font-roboto',
});

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  weight: ['400', '500'],
  display: 'swap',
  variable: '--font-roboto-mono',
});

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://horsetounicorn.com';
const siteDescription =
  'Weekly lessons in marketing and systems thinking for technical founders and operators.';

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: 'Horse to Unicorn',
    template: '%s — Horse to Unicorn',
  },
  description: siteDescription,
  applicationName: 'Horse to Unicorn',
  authors: [{ name: 'Thomas Budin', url: siteUrl }],
  creator: 'Thomas Budin',
  publisher: 'Horse to Unicorn',
  formatDetection: { email: false, address: false, telephone: false },
  alternates: {
    canonical: siteUrl,
    types: {
      'application/rss+xml': `${siteUrl}/rss.xml`,
    },
  },
  openGraph: {
    type: 'website',
    siteName: 'Horse to Unicorn',
    title: 'Horse to Unicorn',
    description: siteDescription,
    url: siteUrl,
    locale: 'en_US',
    // OG image auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Horse to Unicorn',
    description: siteDescription,
    creator: '@thomasbudin',
    // Twitter image auto-generated by app/twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Middleware injects x-pathname so we can hide the public chrome on /admin.
  const h = await headers();
  const pathname = h.get('x-pathname') ?? '';
  const isAdmin = pathname.startsWith('/admin');

  return (
    <html
      lang="en"
      className={`${robotoSerif.variable} ${roboto.variable} ${robotoMono.variable}`}
    >
      <body className="min-h-screen flex flex-col">
        {isAdmin ? null : <SiteHeader />}
        <main className="flex-1">{children}</main>
        {isAdmin ? null : <SiteFooter />}
        {isAdmin ? null : <Analytics />}
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
